- hosts: localhost
  vars:
    ImageName: ""
    Namespace: ""
    imageTag: ""
  #remote_user: ansible
  become: true
  #become_user: true
  gather_facts: no
  connection: local
  tasks:
    - name: Get Namespace {{ Namespace }}
      command: "/usr/local/bin/kubectl version"
      ignore_errors: yes
    - name: Get PO {{ Namespace }}
      command: "/usr/local/bin/kubectl get po -n default"
      ignore_errors: yes
