- hosts: 127.0.0.1
  vars:
    ImageName: "subratit/projects-16th-nov"
    Namespace: "local-namespace-dfly"
    imageTag: "latest02"
  #remote_user: ansible
  become: true
  become_user: root
  gather_facts: no
  connection: local
  tasks:
    - name: Create Namespace {{ Namespace }}
      command: "/usr/local/bin/kubectl get  pod kube-apiserver-docker-desktop -n kube-system"
      ignore_errors: yes
    - name: Get Namespace {{ Namespace }}
      command: "/usr/local/bin/kubectl get pods --all-namespaces"
      ignore_errors: yes
    - name: Check helm version
      command: "/usr/local/bin/helm version"
    - name: Kubernetes Run
      command: "/usr/local/bin/kubectl run kubernetes-container --replicas=2 --image=subratit/projects-16th-nov:latest --port=8181"
      #delegate_to: localhost
      ignore_errors: yes
    - name: Kubernetes Expose
      command: "/usr/local/bin/kubectl expose deployment kubernetes-container --type=LoadBalancer --port=82 --target-port=8181 --name=kubernetes-container"
      delegate_to: localhost
      ignore_errors: yes
