apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfly-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dfly-app
  template:
    metadata:
      labels:
        app: dfly-app
    spec:
      containers:
      - name: dfly-container
        image: subratit/projects-16th-dec1:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: dfly-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dfly-app
        
